### ISSUE TITLE
Docker host network on Mac

### ISSUE THREAD

**Issue by cwysong85** [drachtio/docker-drachtio-freeswitch-mrf#16]
I'm trying my best to not have to dual boot my Mac (install Linux) to get this to work. The "--net=host" doesn't work on Mac due to how docker works on a Mac. I noticed in the advertising of the RTP IP in the SDP, it uses the local docker network address (which is what it was assigned since i tried to **not** use the host machine network). Is there anyway to configure Freeswitch to advertise a different RTP IP and just use Docker port forwarding?

**Comment by cwysong85** [comment]
Here's the INVITE to Jambonz media server and the 200 OK response. The goal would be to have the media server utilize the host machines IP address and just use dockers port forwarding.

Original INVITE IP: `192.168.30.159`
```
INVITE sip:drachtio@172.24.0.3:5080 SIP/2.0
Via: SIP/2.0/UDP 172.24.0.2;rport;branch=z9hG4bKXr9924eKm43ZN
Max-Forwards: 70
From: <sip:172.24.0.2:5060>;tag=UjDUcvrjN88jc
To: <sip:drachtio@172.24.0.3:5080>
Call-ID: 3c1840ed-fceb-123c-fcb9-0242ac180002
CSeq: 75394104 INVITE
Contact: <sip:172.24.0.2:5060>
User-Agent: drachtio-fsmrf:332a065e-3294-4087-9164-949f9ceff668
Content-Type: application/sdp
Content-Length: 345
X-esl-outbound: 192.168.30.159:53172

v=0
o=- 3908866593 3908866593 IN IP4 192.168.30.159
s=pjmedia
b=AS:84
t=0 0
a=X-nat:0
m=audio 4010 RTP/AVP 8 0 101
c=IN IP4 192.168.30.159
b=TIAS:64000
a=rtcp:4011 IN IP4 192.168.30.159
a=sendrecv
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ssrc:222657343 cname:32f90b874edd0908
```

Media server response IP: `172.24.0.3`
```
SIP/2.0 200 OK
Via: SIP/2.0/UDP 172.24.0.2;rport=5060;branch=z9hG4bKXr9924eKm43ZN
From: <sip:172.24.0.2:5060>;tag=UjDUcvrjN88jc
To: <sip:drachtio@172.24.0.3:5080>;tag=BSttaQevg7r9Q
Call-ID: 3c1840ed-fceb-123c-fcb9-0242ac180002
CSeq: 75394104 INVITE
Contact: <sip:drachtio@172.24.0.3:5080;transport=udp>
User-Agent: Jambonz media gateway
Accept: application/sdp
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY
Supported: path, replaces
Allow-Events: talk, hold, conference, refer
Content-Type: application/sdp
Content-Disposition: session
Content-Length: 248
Remote-Party-ID: "drachtio" <sip:drachtio@172.24.0.3>;party=calling;privacy=off;screen=no

v=0
o=FreeSWITCH 1699875791 1699875792 IN IP4 172.24.0.3
s=FreeSWITCH
c=IN IP4 172.24.0.3
t=0 0
m=audio 20002 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=ptime:20
a=rtcp:20003 IN IP4 172.24.0.3
```

**Comment by cwysong85** [comment]
I was able to get it working with this docker-compose.yml file:

```yaml
version: '3.8'

services:
  mrf:
    image: drachtio/drachtio-freeswitch-mrf:latest
    environment:
      - DEEPGRAM_API_KEY=668b294a8ce059e9c725744a7800f5c9e8a12dea
    ports:
      - 5080:5080
      - 8021:8021
      - 20000-20010:20000-20010/udp
    command: freeswitch --ext-rtp-ip 192.168.30.253 --ext-sip-ip 192.168.30.253 --advertise-external-ip --rtp-range-start 20000 --rtp-range-end 20010 
  sip-server:
    image: drachtio/drachtio-server:latest
    ports:
      - 5060:5060
      - 9022:9022
    volumes:
      - ./drachtio.conf.xml:/etc/drachtio.conf.xml
```

And changing the `drachtio.conf.xml` to advertise my host ip:

```xml
    <sip>
        <contacts>
            <contact external-ip="192.168.30.253">sip:*;transport=udp,tcp</contact>
        </contacts>
    </sip>
```
